### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by katjabercic** [MathBases/MathBases#56]
Attending Jennifer Paulhus' talk about LMFDB at [CICM 2024](https://cicm-conference.org/2024/cicm.php) - she stresses the usage statistics. She makes a strong case, should we do it for MathBases, too? (In a nutshell, it makes it easier to argue the relevance of the project.)

It's been a while since I looked into this for static pages, is anyone more up to date (I can check if not).

**Comment by edgarcosta** [comment]
Can you elaborate on what you mean about statistics?
Statistics on LMFDB are by section, and there are no statistics across multiple sections.

@jenpaulhus, could you share your slides? :)

**Comment by jenpaulhus** [comment]
Katja's talking about stats from Google Analytics.  Relevant slide attached!  
[UsageSlide.pdf](https://github.com/user-attachments/files/16517130/UsageSlide.pdf)

**Comment by edgarcosta** [comment]
Thank you @jenpaulhus!

@katjabercic we keep track of similar statistics via umani, but since umani doesn't use cookies, it is harder to keep track of unique users.

**Comment by edgarcosta** [comment]
Ben was the one who set up this.
@diracdeltafunk Could you add us to the unami project?

**Comment by diracdeltafunk** [comment]
The analytics are currently going to my personal umami account, and it looks like I can't share the stats without a pro plan. So, let me make an account for MathBases and transfer the analytics there; I'll share the details with @edgarcosta and @katjabercic via private message on Zulip.

I think the new account will start fresh; i.e. won't show data from before its creation. I've also downloaded all of the data I have now as a CSV, and I have screenshots of some useful graphs umami has generated. I'll share those on Zulip as well.

**Comment by diracdeltafunk** [comment]
We'll need a MathBases email account to set up the new account, I've posted about this on Zulip (MathBases > Analytics).

**Comment by diracdeltafunk** [comment]
Done -- editorial board now has access to the MathBases umami account.

1cd5ec2868c9135923809f55a72e2b2c917b6017
